### PR TITLE
Moving the scripts to Nested Modules

### PR DESCRIPTION
**Pull request by gomker**
Nesting modules to allow for exporting of functions 

Functions now available in Get-Command
```
PS C:\> Get-Command -Module PoshStack

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Add-OpenStackComputeServerVolume                   0.0.1      PoshStack
Function        Add-OpenStackIdentityRoleForUser                   0.0.1      PoshStack
Function        Add-OpenStackObjectStorageObject                   0.0.1      PoshStack
Function        Add-OpenStackObjectStorageObjectFromFile           0.0.1      PoshStack
Function        Clear-OpenStackObjectStorageObjectFromCDN          0.0.1      PoshStack
Function        Confirm-OpenStackDatabaseRootEnabledStatus         0.0.1      PoshStack
Function        Copy-OpenStackObjectStorageObject                  0.0.1      PoshStack
Function        Copy-OpenStackObjectStorageObjectToFile            0.0.1      PoshStack
Function        Disable-OpenStackObjectStorageContainerCDN         0.0.1      PoshStack
Function        Disable-OpenStackObjectStorageStaticWebOnContainer 0.0.1      PoshStack
Function        Edit-OpenStackIdentityUser                         0.0.1      PoshStack
Function        Enable-OpenStackDatabaseRootUser                   0.0.1      PoshStack
Function        Enable-OpenStackObjectStorageContainerCDN          0.0.1      PoshStack
Function        Enable-OpenStackObjectStorageStaticWebOnContainer  0.0.1      PoshStack
Function        Get-OpenStackAccount                               0.0.1      PoshStack
Function        Get-OpenStackBlockStorageProvider                  0.0.1      PoshStack
Function        Get-OpenStackBlockStorageSnapshot                  0.0.1      PoshStack
Function        Get-OpenStackBlockStorageSnapshots                 0.0.1      PoshStack
Function        Get-OpenStackBlockStorageVolume                    0.0.1      PoshStack
Function        Get-OpenStackBlockStorageVolumeType                0.0.1      PoshStack
Function        Get-OpenStackBlockStorageVolumeTypeInfo            0.0.1      PoshStack
Function        Get-OpenStackComputeProvider                       0.0.1      PoshStack
Function        Get-OpenStackComputeServer                         0.0.1      PoshStack
Function        Get-OpenStackComputeServerAddress                  0.0.1      PoshStack
Function        Get-OpenStackComputeServerFlavor                   0.0.1      PoshStack
Function        Get-OpenStackComputeServerImage                    0.0.1      PoshStack
Function        Get-OpenStackComputeServerVolume                   0.0.1      PoshStack
Function        Get-OpenStackComputeServerVolumeDetail             0.0.1      PoshStack
Function        Get-OpenStackDatabase                              0.0.1      PoshStack
Function        Get-OpenStackDatabaseFlavor                        0.0.1      PoshStack
Function        Get-OpenStackDatabaseInstance                      0.0.1      PoshStack
Function        Get-OpenStackDatabasesProvider                     0.0.1      PoshStack
Function        Get-OpenStackDatabaseUser                          0.0.1      PoshStack
Function        Get-OpenStackIdentityProvider                      0.0.1      PoshStack
Function        Get-OpenStackIdentityProviderOpenStack             0.0.1      PoshStack
Function        Get-OpenStackIdentityRole                          0.0.1      PoshStack
Function        Get-OpenStackIdentityTenant                        0.0.1      PoshStack
Function        Get-OpenStackIdentityUser                          0.0.1      PoshStack
Function        Get-OpenStackIdentityUserRole                      0.0.1      PoshStack
Function        Get-OpenStackObjectStorageContainer                0.0.1      PoshStack
Function        Get-OpenStackObjectStorageContainerCDNHeader       0.0.1      PoshStack
Function        Get-OpenStackObjectStorageContainerMetadata        0.0.1      PoshStack
Function        Get-OpenStackObjectStorageHeader                   0.0.1      PoshStack
Function        Get-OpenStackObjectStorageObject                   0.0.1      PoshStack
Function        Get-OpenStackObjectStorageObjectHeader             0.0.1      PoshStack
Function        Get-OpenStackObjectStorageObjectMetadata           0.0.1      PoshStack
Function        Get-OpenStackObjectStorageProvider                 0.0.1      PoshStack
Function        Grant-CloudDatabaseUserAccess                      0.0.1      PoshStack
Function        Initialize-OpenStackComputeServer                  0.0.1      PoshStack
Function        Invoke-Exception                                   0.0.1      PoshStack
Function        Move-OpenStackObjectStorageObject                  0.0.1      PoshStack
Function        New-OpenStackBlockStorageSnapshot                  0.0.1      PoshStack
Function        New-OpenStackBlockStorageVolume                    0.0.1      PoshStack
Function        New-OpenStackComputeServer                         0.0.1      PoshStack
Function        New-OpenStackComputeServerImage                    0.0.1      PoshStack
Function        New-OpenStackDatabase                              0.0.1      PoshStack
Function        New-OpenStackDatabaseInstance                      0.0.1      PoshStack
Function        New-OpenStackDatabaseUser                          0.0.1      PoshStack
Function        New-OpenStackIdentityUser                          0.0.1      PoshStack
Function        New-OpenStackObjectStorageContainer                0.0.1      PoshStack
Function        New-RandomComplexPassword                          0.0.1      PoshStack
Function        Remove-OpenStackBlockStorageSnapshot               0.0.1      PoshStack
Function        Remove-OpenStackBlockStorageVolume                 0.0.1      PoshStack
Function        Remove-OpenStackComputeServer                      0.0.1      PoshStack
Function        Remove-OpenStackDatabase                           0.0.1      PoshStack
Function        Remove-OpenStackDatabaseInstance                   0.0.1      PoshStack
Function        Remove-OpenStackDatabaseUser                       0.0.1      PoshStack
Function        Remove-OpenStackIdentityRoleFromUser               0.0.1      PoshStack
Function        Remove-OpenStackIdentityUser                       0.0.1      PoshStack
Function        Remove-OpenStackObjectStorageContainer             0.0.1      PoshStack
Function        Remove-OpenStackObjectStorageContainerMetadata     0.0.1      PoshStack
Function        Remove-OpenStackObjectStorageObject                0.0.1      PoshStack
Function        Remove-OpenStackObjectStorageObjectMetadata        0.0.1      PoshStack
Function        Remove-OpenStackObjectStorageObjects               0.0.1      PoshStack
Function        Resize-OpenStackComputeServer                      0.0.1      PoshStack
Function        Restart-OpenStackComputeServer                     0.0.1      PoshStack
Function        Restart-OpenStackDatabaseInstance                  0.0.1      PoshStack
Function        Revoke-OpenStackDatabaseUserAccess                 0.0.1      PoshStack
Function        Set-OpenStackComputeServerAdministratorPassword    0.0.1      PoshStack
Function        Set-OpenStackDatabaseInstanceSize                  0.0.1      PoshStack
Function        Set-OpenStackDatabaseInstanceVolumeSize            0.0.1      PoshStack
Function        Set-OpenStackDatabaseUserPassword                  0.0.1      PoshStack
Function        Show-OpenStackAccounts                             0.0.1      PoshStack
Function        Show-UntestedWarning                               0.0.1      PoshStack
Function        Test-OpenStackObjectStorageContainerCDNEnabled     0.0.1      PoshStack
Function        Update-OpenStackComputeServer                      0.0.1      PoshStack
Function        Update-OpenStackObjectStorageContainerCDNHeader    0.0.1      PoshStack
Function        Update-OpenStackObjectStorageContainerMetadata     0.0.1      PoshStack
Function        Update-OpenStackObjectStorageObjectMetadata        0.0.1      PoshStack
Function        Watch-OpenStackBlockStorageSnapshotAvailable       0.0.1      PoshStack
Function        Watch-OpenStackBlockStorageVolumeAvailable         0.0.1      PoshStack
Function        Watch-OpenStackBlockStorageVolumeDeleted           0.0.1      PoshStack
Function        Watch-OpenStackBlockStorageVolumeState             0.0.1      PoshStack


PS C:\>
```

### CODE REVIEW

**Comment by DonSchenck** [comment]
Will review and this and -- assuming it's awesome -- merge it, today.

**Comment by DonSchenck** [comment]
Derek, can you "rebase on master" to remove the conflicts?

**Comment by gomker** [comment]
Don, sorry about that - rebased according to https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by DonSchenck** [comment]
Awesome work, and thanks Derek! Feel free to contribute more. :)

**Pull request merged**
